# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apm/v1/action.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import tag_pb2 as shared_dot_tag__pb2
from shared import measurement_pb2 as shared_dot_measurement__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='apm/v1/action.proto',
  package='palantir.apm.v1.action',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x61pm/v1/action.proto\x12\x16palantir.apm.v1.action\x1a\x10shared/tag.proto\x1a\x18shared/measurement.proto\"\xff\x01\n\x0b\x41pmV1Action\x12\r\n\x05realm\x18\x01 \x01(\t\x12\x13\n\x0b\x61pplication\x18\x02 \x01(\t\x12\x18\n\x10\x61pplication_hash\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63tion_kind\x18\x04 \x01(\t\x12\x13\n\x0b\x61\x63tion_name\x18\x05 \x01(\t\x12\x10\n\x08total_us\x18\x06 \x01(\x04\x12>\n\x0cmeasurements\x18\x07 \x03(\x0b\x32(.palantir.shared.measurement.Measurement\x12\x36\n\x14\x61\x64\x64itionalDimensions\x18\x08 \x03(\x0b\x32\x18.palantir.shared.tag.Tagb\x06proto3'
  ,
  dependencies=[shared_dot_tag__pb2.DESCRIPTOR,shared_dot_measurement__pb2.DESCRIPTOR,])




_APMV1ACTION = _descriptor.Descriptor(
  name='ApmV1Action',
  full_name='palantir.apm.v1.action.ApmV1Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='realm', full_name='palantir.apm.v1.action.ApmV1Action.realm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application', full_name='palantir.apm.v1.action.ApmV1Action.application', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application_hash', full_name='palantir.apm.v1.action.ApmV1Action.application_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_kind', full_name='palantir.apm.v1.action.ApmV1Action.action_kind', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_name', full_name='palantir.apm.v1.action.ApmV1Action.action_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_us', full_name='palantir.apm.v1.action.ApmV1Action.total_us', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurements', full_name='palantir.apm.v1.action.ApmV1Action.measurements', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='additionalDimensions', full_name='palantir.apm.v1.action.ApmV1Action.additionalDimensions', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=347,
)

_APMV1ACTION.fields_by_name['measurements'].message_type = shared_dot_measurement__pb2._MEASUREMENT
_APMV1ACTION.fields_by_name['additionalDimensions'].message_type = shared_dot_tag__pb2._TAG
DESCRIPTOR.message_types_by_name['ApmV1Action'] = _APMV1ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApmV1Action = _reflection.GeneratedProtocolMessageType('ApmV1Action', (_message.Message,), {
  'DESCRIPTOR' : _APMV1ACTION,
  '__module__' : 'apm.v1.action_pb2'
  # @@protoc_insertion_point(class_scope:palantir.apm.v1.action.ApmV1Action)
  })
_sym_db.RegisterMessage(ApmV1Action)


# @@protoc_insertion_point(module_scope)
