# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apm.v1 import action_pb2 as apm_dot_v1_dot_action__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='palantir.request',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrequest.proto\x12\x10palantir.request\x1a\x13\x61pm/v1/action.proto\"R\n\x07Request\x12<\n\rapm_v1_action\x18\x01 \x01(\x0b\x32#.palantir.apm.v1.action.ApmV1ActionH\x00\x42\t\n\x07messageb\x06proto3'
  ,
  dependencies=[apm_dot_v1_dot_action__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='palantir.request.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='apm_v1_action', full_name='palantir.request.Request.apm_v1_action', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='palantir.request.Request.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=56,
  serialized_end=138,
)

_REQUEST.fields_by_name['apm_v1_action'].message_type = apm_dot_v1_dot_action__pb2._APMV1ACTION
_REQUEST.oneofs_by_name['message'].fields.append(
  _REQUEST.fields_by_name['apm_v1_action'])
_REQUEST.fields_by_name['apm_v1_action'].containing_oneof = _REQUEST.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:palantir.request.Request)
  })
_sym_db.RegisterMessage(Request)


# @@protoc_insertion_point(module_scope)
